<a href="https://colab.research.google.com/github/ccc3995/Python/blob/main/Chap4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#numpy套件(numeric python)
#為什麼需要numpy?


* numpy由c撰寫，速度快python 10~1000倍以上
* numpy儲存結果較正確，python數字儲存不正確
* numpy節省記憶體儲存空間
* numpy的向量(矩陣計算)速度快
* numpy的取值方便

In [ ]:
a_list=[1,2,3,4,5]
print(a_list*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
#numpy套件的ndarray型態,提供lement-wise的操作
import numpy as np
a=np.array([1,2,3,4,5])
print(a*3)

[ 3  6  9 12 15]


In [ ]:
a=np.array([1,2,3,4,5])
print(type(a))
print(a.shape)
print(a.dtype)
print(a.ndim)

<class 'numpy.ndarray'>
(5,)
int64
1


In [ ]:
import numpy as np
z=np.zeros(6)
print(z)
print(np.empty((2,3,4)))
print(np.arange(10))

[0. 0. 0. 0. 0. 0.]
[[[1.718286e-316 0.000000e+000 0.000000e+000 0.000000e+000]
  [0.000000e+000 0.000000e+000 0.000000e+000 0.000000e+000]
  [0.000000e+000 0.000000e+000 0.000000e+000 0.000000e+000]]

 [[0.000000e+000 0.000000e+000 0.000000e+000 0.000000e+000]
  [0.000000e+000 0.000000e+000 0.000000e+000 0.000000e+000]
  [0.000000e+000 0.000000e+000 0.000000e+000 0.000000e+000]]]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np
a=np.zeros([0,1,2,3,4])
print(z)
print(np.empty((2,3,4)))
print(np.arange(10))

# 2維資料取值

In [ ]:
my_2d_array=np.array([np.arange(0,5),np.arange(5,10)])
print(my_2d_array)
print(my_2d_array[1,:]) #取第"1"维的值
print(my_2d_array[:,1]) #取第"0","1"维中，第"1"维的值
print(my_2d_array[1,2]) #取第"1","2"维中，第"2"维的值

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
7


In [ ]:
#更改維度reshape
a=np.arange(10) #一維10個數字
print(a)
b=a.reshape(2,5)#更改成二維，每維5個數字
print(b)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
my_array-np.arange(0, 10)
print(my_array)
print(my_array.shape)